// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDan1lxdaQn3PzLdSn5g0j2YmlV1LjU2rs',
    appId: '1:622176680649:web:080fcbbe828d8042f62b18',
    messagingSenderId: '622176680649',
    projectId: 'fire-dd053',
    authDomain: 'fire-dd053.firebaseapp.com',
    storageBucket: 'fire-dd053.firebasestorage.app',
    measurementId: 'G-0NVMY7LSKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mMiQAUBBAJVsGZvtFd95aSNHuMpYgdk',
    appId: '1:622176680649:android:7bd40aad3c27c99af62b18',
    messagingSenderId: '622176680649',
    projectId: 'fire-dd053',
    storageBucket: 'fire-dd053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmyXnWPFMaOuPu6cvA8Aa3pEjHLzNw8N4',
    appId: '1:622176680649:ios:58760d61da2cd9f6f62b18',
    messagingSenderId: '622176680649',
    projectId: 'fire-dd053',
    storageBucket: 'fire-dd053.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmyXnWPFMaOuPu6cvA8Aa3pEjHLzNw8N4',
    appId: '1:622176680649:ios:58760d61da2cd9f6f62b18',
    messagingSenderId: '622176680649',
    projectId: 'fire-dd053',
    storageBucket: 'fire-dd053.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDan1lxdaQn3PzLdSn5g0j2YmlV1LjU2rs',
    appId: '1:622176680649:web:b1ecee2fef9c87a0f62b18',
    messagingSenderId: '622176680649',
    projectId: 'fire-dd053',
    authDomain: 'fire-dd053.firebaseapp.com',
    storageBucket: 'fire-dd053.firebasestorage.app',
    measurementId: 'G-5ZX62RCWHE',
  );
}
